//#define PREFER_SIZE_OVER_SPEED 1
#include "defs.h"
#include "string.h"

#include "memcmp.c"
#include "memmove.c"
#include "memset.c"
//#include "strcat.c"
#include "strcpy.c"
#include "strncpy.c"
#include "strcmp.c"
#include "strncmp.c"
#include "strlen.c"
#include "ctype.c"
#include "strtol.c"
#include "strtoul.c"
